### ISSUE TITLE
documentation links are wrong

### ISSUE THREAD

**Issue by alexeymuranov** [ghcformacosx/ghc-dot-app#33] opened 2015-04-07 17:03 UTC
Clicking "Open GHC Docs" opens a local page. Clicking then, for example, "Libraries", opens another local page.  Clicking then almost anything does not open anything, because links are bad.

**Comment by etrepum** [comment] 2015-04-07 21:34
I can reproduce, something must've changed in GHC 7.10.

**Comment by elfenlaid** [comment] 2015-04-18 09:18
yep, I'm also can't download *7.10.1-r0* with `Error code: ERR_CONNECTION_REFUSED`

**Comment by etrepum** [comment] 2015-04-18 13:10
Your issue with downloading is unrelated to this. Downloads are hosted by GitHub.

**Comment by elfenlaid** [comment] 2015-04-18 13:20
oh, I see, sorry for disturbing

**Comment by adityav** [comment] 2015-06-26 17:36
I am facing the same problem

**Comment by etrepum** [comment] 2015-06-28 01:40
The root cause for this is in GHC build process somewhere, hopefully will be fixed in 7.10.2.

**Comment by etrepum** [comment] 2015-08-01 01:46
GHC 7.10.2 doesn't seem to have this problem

**Closed by etrepum** 2015-08-01 01:46 UTC
