### ISSUE TITLE
 GHC-7.10.2-r0 has `ar` permission errors due to rootless on OS X 10.11

### ISSUE THREAD

**Issue by LukeHoersten** [ghcformacosx/ghc-dot-app#41] opened 2015-08-04 21:43 UTC
ghc-7.10.2-r0.zip has the same issue that https://github.com/ghcformacosx/ghc-dot-app/issues/39 has. It wasn't an issue with the 7.10.1 release though. Looks like a regression with the `unix` version.

**Comment by etrepum** [comment] 2015-08-05 00:30
*shrug* this must be a bug upstream in GHC. Can you reproduce with their installation? https://github.com/ghcformacosx/ghc-dot-app/blob/master/Main.hs#L126-L132

**Comment by LukeHoersten** [comment] 2015-08-05 13:34
I think it's an issue with the `cabal-install` being packaged in not the GHC version. https://github.com/ghcformacosx/ghc-dot-app/blob/master/Main.hs#L137

**Comment by glguy** [comment] 2015-09-02 21:23
I was able to get my GHC.app installation working by copying over a new cabal-install binary built on my 10.10 machine against the latest libraries. My understanding is that this bug was fixed in unix-2.7.1.0 which is what I built against.

**Comment by LukeHoersten** [comment] 2015-09-02 22:44
Yes that's correct. The `cabal-install` packaged with GHC.app is built against the old version of `unix`.

**Comment by evancz** [comment] 2015-10-01 01:01
I am seeing the same thing using GHC-7.10.2-r0 on El Capitan.

```
cabal: /usr/bin/ar: permission denied
```

**Comment by gbaz** [comment] 2015-10-01 05:01
El Capitan is out officially now, so it would be good to get this fixed as it will start to become more urgent for more users over the next few weeks.

**Comment by etrepum** [comment] 2015-10-01 08:26
I'm traveling for the next week and don't have the internet bandwidth (or laptop death wish to upgrade OS X while on the road) to do a release before then. Happy to give someone else access if they can and want to test and do a build before then.

**Comment by evancz** [comment] 2015-10-01 09:24
@LukeHoersten, you linked to a bad not-working tar, can you link to one that works? Or do I need to build from source? What is the stopgap here?

**Comment by LukeHoersten** [comment] 2015-10-01 14:55
@evancz The tar I linked is the one being used by GHC.app which is broken. GHC.app doesn't use an official build of GHC apparently.

**Comment by etrepum** [comment] 2015-10-01 14:59
GHC.app uses an official build of GHC. No official build of cabal was available, so the next best thing (halcyon's build) was chosen.

**Comment by LukeHoersten** [comment] 2015-10-01 15:01
Ah I'm sorry that's what I meant. Cabal build not GHC.

**Comment by LukeHoersten** [comment] 2015-10-01 15:03
My point in linking that cabal tar was that it's the Halcyon cabal that's broken. Sorry if that wasn't clear. I was not trying to post a working cabal-install bin.

**Comment by evancz** [comment] 2015-10-01 19:17
Okay, but can you post a working one too? ;)

If not, who should I talk to who could build it correctly and post such a thing? As I understand, it is 100% not necessary to build on El Capitan, you just have to make sure you get the `unix` dependency right. Seems like this wouldn't be too hard if you already know how to build cabal.

Or do I need to figure out how to build cabal from source myself to get things working? (I really hope there's someone who knows *anything* about this process that can do this instead of me though.)

**Comment by LukeHoersten** [comment] 2015-10-01 19:33
You can disable rootless on your mac, use the broken cabal-install to build
and install a later cabal-install with the latest unix and then re-enable
rootless.

**Comment by evancz** [comment] 2015-10-01 19:45
Okay, it looks like disabling rootless [got a bit harder](https://gist.github.com/djtech42/7233c602fda912d96fdf). The `nvram` thing does not work for me, and it looks like it does not work for the actual release either. I'm not sure it'll stay rootless if I move outside of recovery mode, but I guess I have to give it a go.

(Now it seems that it's actually easier to do this from *not* El Capitan.)

**Comment by evancz** [comment] 2015-10-01 19:47
Okay, it looks like [it's possible to stay rootless after a reboot](https://forums.developer.apple.com/thread/3981).

Should I share the binary I create with someone in particular if I succeed?

**Comment by evancz** [comment] 2015-10-01 20:24
Okay, here is [the binary](https://www.dropbox.com/s/rvvjlcmd85yyvy5/cabal?dl=0) I created if that is helpful to anyone. I am out of rootless mode now, and it is working fine. I'm planning to take it down as soon as this issue is closed though.

**Comment by technocrat** [comment] 2015-10-02 04:37
Thanks @evancz; the combo of your cabal (after I remembered to chmod +x it), 7.10.2-a and disabling rootless worked for me on EC release to get past 

    cabal: /usr/bin/ar: permission denied

and my system is happily re-re-installing pandoc

**Comment by pellagic-puffbomb** [comment] 2015-10-06 17:51
I just want to mention that I was able to get my system working again *only* by using the binary provided by @evancz  (thanks, :tophat: )

I didn't need to disable rootless.

**Comment by etrepum** [comment] 2015-10-06 18:07
Good news, I'll post a new build this weekend when I'm back in the US

**Comment by evancz** [comment] 2015-10-06 19:40
Yeah, to be clear to anyone from the internet reading this: I needed to go disable the rootless stuff to *build* the binary, but you can use it on a mac just by downloading it. No need to do anything weird. Just put the binary in the place of the other one. And you can use `which cabal` to figure out where things should go.

**Comment by Alehanz** [comment] 2015-10-09 21:55
Thanks, @evancz! Super helpful.

**Comment by etrepum** [comment] 2015-10-14 14:53
The easiest workaround for this is to either just use `stack`, or to use `stack` to build `cabal-install`.

```bash
$ stack install cabal-install
…
$ hash -r
# now you have a cabal that works
```

Will take another day or two for me to get a build out.

**Comment by etrepum** [comment] 2015-10-14 14:54
Note that `stack` already ships with the build.

**Comment by GetContented** [comment] 2015-10-15 03:14
@evancz thank you! I was already using stack and I had the same problem(s).

**Comment by adam-r-kowalski** [comment] 2015-10-25 06:18
@evancz the binary worked great, thanks! I did have to chmod +x it to get it working like @technocrat said. 

@etrepum I tried to install the latest cabal-install using stack and for whatever reason it still had a permission error for /usr/bin/ar with el capitan for me.

**Comment by desbo** [comment] 2015-11-03 22:47
Thanks @etrepum – I was getting `/usr/bin/ar: permission denied` after a clean install of ghc-7.10.2-r0. `stack install cabal-install` fixed things for me.

**Comment by gbaz** [comment] 2015-11-06 01:28
@etrepum any eta on the build?

**Comment by alexito4** [comment] 2015-12-13 18:03
I can confirm that the binary provided by @evancz works ;) Remember to add executable permissions to it after moving it into the .app 
:+1:

**Comment by paparent** [comment] 2016-01-21 23:31
Is this fixed? just downloaded today the app and I get the error.. I followed the steps on the homepage.

**Comment by TazeTSchnitzel** [comment] 2016-02-11 03:01
It's not fixed, I got it too.

**Closed** 2016-02-20 23:39 UTC

**Comment by gbaz** [comment] 2016-02-24 02:01
Here's the working cabal from the platform build if that helps.
